from lambdaman.lambdagraph import LambdaMap

map_file = "..//problems/lambdaman5.txt"

"""
.....########...
....#...........
...#..######....
..#..#......#...
.#..#...##...#..
.#..#..#L.#...#.
.#...#....#...#.
..#...####...#..
...#........#...
....########....
................
"""

G = LambdaMap(map_file)

"""
[[ 5  7  7  7  2  0  0  0  0  0  0  0  0  5  7  6]
 [13 15 15 10  0  5  3  3  3  3  3  3  7 15 15 14]
 [13 15 10  0  5 10  0  0  0  0  0  0  9 15 15 14]
 [13 10  0  5 10  0  5  7  3  3  7  6  0  9 15 14]
 [12  0  5 14  0  5 15 10  0  0  9 15  6  0  9 14]
 [12  0 13 14  0  9 14  0  5  6  0 13 15  6  0 12]
 [12  0  9 15  6  0  9  3 11 10  0 13 15 10  0 12]
 [13  6  0  9 15  6  0  0  0  0  5 15 10  0  5 14]
 [13 15  6  0  9 11  3  3  3  3 11 10  0  5 15 14]
 [13 15 15  6  0  0  0  0  0  0  0  0  5 15 15 14]
 [ 9 11 11 11  3  3  3  3  3  3  3  3 11 11 11 10]]
(5, 8)
"""

print(G.lazy_path) # RDULDLLULRDRRUDLLUULRDDRRUDLLUUUDDDRRUDLLUURURRRDULLLDLDDRRUDLLUURURRRRDDDRDULUUULLLLDLDDRRUDLLUURURRRRDDDDLRUUUULLLLDLDDRRUDLLUURURRRRDRDRDULULULLLLDLDDRRUDLLUURURRRRDDDDDLLLLLLLRRRRRRRUUUUULLLLDLDDRRUDLLUURURRRRDDDDDLLLLLLULLRRDRRRRRRUUUUULLLLDLDDRRUDLLUURURRRRDDDDDLLLLLLULULLRRDRDRRRRRRUUUUULLLLDLDDRRUDLLUURURRRRDDDDDLLLLLLULULULRDRDRDRRRRRRUUUUULLLLDLDDRRUDLLUURURRRRDDDDDLLLLLLULULUULRDDRDRDRRRRRRUUUUULLLLDLDDRRUDLLUURURRRRDDDDDLLLLLLULULUUURURURRRRRRRDULLLLLLLDLDLDDDRDRDRRRRRRUUUUULLLLDLDDRRUDLLUURURRRRDDDDDLLLLLLULULUUURURURRRRRRRRUDLLLLLLLLDLDLDDDRDRDRRRRRRUUUUULLLLDLDDRRUDLLUURURRRRDDDDDLLLLLLULULUUURURURRRRRRRRRDULLLLLLLLLDLDLDDDRDRDRRRRRRUUUUULLLLDLDDRRUDLLUURURRRRDDDDDLLLLLLULULUUURURURRRRRRRRRUDLLLLLLLLLDLDLDDDRDRDRRRRRRUUUUULLLLDLDDRRUDLLUURURRRRDDDDDLLLLLLULULUUURURURRRRRRRRRRUDLLLLLLLLLLDLDLDDDRDRDRRRRRRUUUUULLLLDLDDRRUDLLUURURRRRDDDDDLLLLLLULULUUURURURRRRRRRRRRDDUULLLLLLLLLLDLDLDDDRDRDRRRRRRUUUUULLLLDLDDRRUDLLUURURRRRDDDDDLLLLLLULULUUURURURRRRRRRRDDRDRDDDLRUUULULUULLLLLLLLDLDLDDDRDRDRRRRRRUUUUULLLLDLDDRRUDLLUURURRRRDDDDDLLLLLLULULUUURURURRRRRRRRDDRDRDDDDDLRUUUUULULUULLLLLLLLDLDLDDDRDRDRRRRRRUUUUULLLLDLDDRRUDLLUURURRRRDDDDDLLLLLLULULUUURURURRRRRRRRDDRDRDDDDDDLLRRUUUUUULULUULLLLLLLLDLDLDDDRDRDRRRRRRUUUUULLLLDLDDRRUDLLUURURRRRDDDDDLLLLLLULULUUURURURRRRRRRRDDRDRDDDDLLDLDLLLLLLLLLLLLRRRRRRRRRRRRURURRUUUULULUULLLLLLLLDLDLDDDRDRDRRRRRRUUUUULLLLDLDDRRUDLLUURURRRRDDDDDLLLLLLULULUUURURURRRRRRRRDDRDRDDDDLLDLDLLLLLLLLLLLULUDRDRRRRRRRRRRRURURRUUUULULUULLLLLLLLDLDLDDDRDRDRRRRRRUUUUULLLLDLDDRRUDLLUURURRRRDDDDDLLLLLLULULUUURURURRRRRRRRDDRDRDDDDLLDLDLLLLLLLLLULULULUUUUUUUDDDDDDDRDRDRDRRRRRRRRRURURRUUUULULUULLLLLLLLDLDLDDDRDRDRRRRRRUUUUULLLLDLDDRRUDLLUURURRRRDDDDDLLLLLLULULUUURURURRRRRRRRDDRDRDDDDLLDLDLLLLLLLLLULULULUUUUUURURLDLDDDDDDRDRDRDRRRRRRRRRURURRUUUULULUULLLLLLLLDLDLDDDRDRDRRRRRRUUUUULLLLDLDDRRUDLLUURURRRRDDDDDLLLLLLULULUUURURURRRRRRRRDDRDRDDDDLLDLDLLLLLLLLLULULULUUUURURURURLDLDLDLDDDDRDRDRDRRRRRRRRRURURRUUUULULUULLLLLLLLDLDLDDDRDRDRRRRRRUUUUULLLLDLDDRRU