from lambdaman.lambdagraph import LambdaMap

map_file = "..//problems/lambdaman5.txt"

"""
.....########...
....#...........
...#..######....
..#..#......#...
.#..#...##...#..
.#..#..#L.#...#.
.#...#....#...#.
..#...####...#..
...#........#...
....########....
................
"""

G = LambdaMap(map_file)

lazy_tsp = G.lazy_tsp()

print(f"solve lambdaman5 {lazy_tsp}")